### ISSUE TITLE
MCAD libraries

### ISSUE THREAD

**Issue by epoxi** [hyperair/fan-blades#1]
Is it possible that the MCAD libraries implementations are outdated?

I'm using linux, and cloned MCAD libreries under ~/.local/share/OpenSCAD/MCAD from https://github.com/SolidCode/MCAD

The code gives me this error:

WARNING: Can't open include file 'MCAD/units/metric.scad'. 
WARNING: Can't open library 'MCAD/array/along_curve.scad'. 
WARNING: Can't open library 'MCAD/shapes/cylinder.scad'. 
WARNING: Can't open library 'scad-utils/transformations.scad'. 
WARNING: Can't open library 'scad-utils/shapes.scad'. 
WARNING: Can't open library 'MCAD/general/sweep.scad'. 
WARNING: Can't open library 'MCAD/shapes/2Dshapes.scad'. 
Compiling design (CSG Tree generation)...
WARNING: Ignoring unknown module 'mcad_rounded_cylinder'. 
WARNING: Ignoring unknown variable 'epsilon'. 
WARNING: Ignoring unknown module 'mcad_rotate_multiply'. 
WARNING: Ignoring unknown module 'mcad_rotate_multiply'. 
Compiling design (CSG Products generation)...
Geometries in cache: 15
Geometry cache size in bytes: 843624
CGAL Polyhedrons in cache: 3
CGAL cache size in bytes: 4294632
Compiling design (CSG Products normalization)...
Normalized CSG tree has 3 elements
Compile and preview finished.
Total rendering time: 0 hours, 0 minutes, 0 seconds

Thanks!!

**Comment by hyperair** [comment]
Yeah wrong one. I'm using the [dev branch of openscad/MCAD](https://github.com/openscad/MCAD/tree/dev/).

**Comment by hyperair** [comment]
Also you need [scad-utils](https://github.com/OskarLinde/scad-utils).

**Comment by epoxi** [comment]
Hi! I think the MCAD/dev repo did it. But I think now the problem is with the scad-utils.
In line five it says:

"use <scad-utils/shapes.scad>"

That library isn't in scad-utils directory. I'm using penSCAD version 2015.03-1

Now the error log is:

WARNING: Can't open library 'scad-utils/shapes.scad'. 
Compiling design (CSG Tree generation)...
WARNING: Ignoring unknown function 'rectangle_profile'. 
WARNING: Ignoring unknown function 'rectangle_profile'. 
WARNING: Ignoring unknown function 'to_3d'. 
WARNING: Ignoring unknown function 'flatten'. 
WARNING: Ignoring unknown function 'rectangle_profile'. 
WARNING: Ignoring unknown function 'rectangle_profile'. 
WARNING: Ignoring unknown function 'to_3d'. 
WARNING: Ignoring unknown function 'flatten'. 
WARNING: Ignoring unknown function 'rectangle_profile'. 
WARNING: Ignoring unknown function 'rectangle_profile'. 
WARNING: Ignoring unknown function 'to_3d'. 
WARNING: Ignoring unknown function 'flatten'. 
WARNING: Ignoring unknown function 'rectangle_profile'. 
WARNING: Ignoring unknown function 'rectangle_profile'. 
WARNING: Ignoring unknown function 'to_3d'. 
WARNING: Ignoring unknown function 'flatten'. 
WARNING: Ignoring unknown function 'rectangle_profile'. 
WARNING: Ignoring unknown function 'rectangle_profile'. 
WARNING: Ignoring unknown function 'to_3d'. 
WARNING: Ignoring unknown function 'flatten'. 
WARNING: Ignoring unknown function 'rectangle_profile'. 
WARNING: Ignoring unknown function 'rectangle_profile'. 
WARNING: Ignoring unknown function 'to_3d'. 
WARNING: Ignoring unknown function 'flatten'. 
Rendering Polygon Mesh using CGAL...
Geometries in cache: 65
Geometry cache size in bytes: 2937272
CGAL Polyhedrons in cache: 19
CGAL cache size in bytes: 36008592
Total rendering time: 0 hours, 0 minutes, 0 seconds
   Top level object is a 3D object:
   Simple:        yes
   Vertices:     6475
   Halfedges:   30910
   Edges:       15455
   Halffacets:  17988
   Facets:       8994
   Volumes:         8
Rendering finished.

**Comment by hyperair** [comment]
Clone scad-utils to ~/.local/share/OpenSCAD/libraries/scad-utils/. Same as MCAD.

**Comment by epoxi** [comment]
Hi! Thanks for your time!

What I'm triying to say is that "shapes.scad" is not part of the "scad-utils" library. Check the file list at https://github.com/OskarLinde/scad-utils

**Comment by hyperair** [comment]
On Tue, Jun 02, 2015 at 10:36:03AM -0700, Lucas Campa wrote:

> Hi! Thanks for your time!
> 
> What I'm triying to say is that "shapes.scad" is not part of the "scad-utils" library. Check the file list at https://github.com/OskarLinde/scad-utils

Oh yeah, you're right. Whoops. It's https://github.com/openscad/scad-utils.

## 

Kind regards,
Loong Jin

**Comment by epoxi** [comment]
Now it works!!! Thanks!!!

Maybe it would be great if you could add the needed librearies (and links) to a README.TXT.

Great work with this parametric Fan Blades code! I'll be testing it tonight. I'l try to replicate this FAN:

![image](https://cloud.githubusercontent.com/assets/1245806/7945213/b56eae84-0945-11e5-9011-77540b536f4e.png)

Thanks Again!!!

**Comment by hyperair** [comment]
On Tue, Jun 02, 2015 at 12:38:08PM -0700, Lucas Campa wrote:

> Now it works!!! Thanks!!!
> 
> Maybe it would be great if you could add the needed librearies (and links) to a README.TXT.

Done, thanks for the suggestion.

> Great work with this parametric Fan Blades code! I'll be testing it tonight. I'l try to replicate this FAN:
> 
> ![image](https://cloud.githubusercontent.com/assets/1245806/7945213/b56eae84-0945-11e5-9011-77540b536f4e.png)

Great. Good luck. :)

## 

Kind regards,
Loong Jin
